In [28]:
import pandas as pd

In [29]:
df=pd.read_csv("../data/indian_banking_transactions.csv")

In [30]:
df.isnull().sum()

transaction_id                0
customer_id                   0
transaction_date              0
transaction_time              0
account_type                  0
transaction_type              0
transaction_amount            0
transaction_direction         0
account_balance               0
merchant_category             0
state                         0
credit_score                  0
has_loan                      0
loan_type                377134
emi_amount                    0
transaction_status            0
channel                       0
kyc_status                    0
is_fraud                      0
transaction_hour              0
dtype: int64

In [31]:
df["has_loan"].value_counts()

has_loan
0    357712
1    192288
Name: count, dtype: int64

In [32]:
pd.crosstab(df["has_loan"],df["loan_type"],dropna=False)

loan_type   Auto  Business  Education  Gold   Home  Personal     NaN
has_loan
0              0         0          0     0      0         0  357712
1          29219     28863      19074  9648  38252     47810   19422

In [33]:
df[(df["has_loan"]==1)& (df["loan_type"].isnull()).head()]

Empty DataFrame
Columns: [transaction_id, customer_id, transaction_date, transaction_time, account_type, transaction_type, transaction_amount, transaction_direction, account_balance, merchant_category, state, credit_score, has_loan, loan_type, emi_amount, transaction_status, channel, kyc_status, is_fraud, transaction_hour]
Index: []

In [34]:
df[(df["has_loan"]==1) & (df["loan_type"].isnull())].shape

(19422, 20)

In [35]:
missing_loan_type=df[
    (df["has_loan"]==1)&
    (df["loan_type"].isnull())
]
print("Rows with missing_loan_type:",len(missing_loan_type))
print("percentage:", round(len(missing_loan_type)/len(df)*100,2),"%")

Rows with missing_loan_type: 19422
percentage: 3.53 %

In [36]:
df.groupby("has_loan")["loan_type"].apply(lambda x:x.isnull().mean()*100)

has_loan
0    100.000000
1     10.100474
Name: loan_type, dtype: float64

In [37]:
df.loc[
    (df["has_loan"]==0)&(df["loan_type"].isnull()),"loan_type"]="No Loan"

df.loc[
    (df["has_loan"]==1)&(df["loan_type"].isnull()),"loan_type"]="Unkown"

In [38]:
df["loan_type"].value_counts(dropna=False)

loan_type
No Loan      357712
Personal      47810
Home          38252
Auto          29219
Business      28863
Unkown        19422
Education     19074
Gold           9648
Name: count, dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df["transaction_id"].duplicated().sum()

np.int64(0)

In [41]:
df.dtypes

transaction_id               str
customer_id                  str
transaction_date             str
transaction_time             str
account_type                 str
transaction_type             str
transaction_amount       float64
transaction_direction        str
account_balance          float64
merchant_category            str
state                        str
credit_score               int64
has_loan                   int64
loan_type                    str
emi_amount               float64
transaction_status           str
channel                      str
kyc_status                   str
is_fraud                   int64
transaction_hour           int64
dtype: object

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   transaction_id         550000 non-null  str
 1   customer_id            550000 non-null  str
 2   transaction_date       550000 non-null  str
 3   transaction_time       550000 non-null  str
 4   account_type           550000 non-null  str
 5   transaction_type       550000 non-null  str
 6   transaction_amount     550000 non-null  float64
 7   transaction_direction  550000 non-null  str
 8   account_balance        550000 non-null  float64
 9   merchant_category      550000 non-null  str
 10  state                  550000 non-null  str
 11  credit_score           550000 non-null  int64
 12  has_loan               550000 non-null  int64
 13  loan_type              550000 non-null  str
 14  emi_amount             550000 non-null  float64
 15  transaction_status     550000 non-null  str
 16  channel                550000 non-null  str
 17  kyc_status             550000 non-null  str
 18  is_fraud               550000 non-null  int64
 19  transaction_hour       550000 non-null  int64
dtypes: float64(3), int64(4), str(13)
memory usage: 83.9 MB

In [43]:
# convertinf transaction_date to datetime format
df["transaction_date"]=pd.to_datetime(df["transaction_date"],errors="coerce")

In [44]:
df["transaction_date"].dtype

dtype('<M8[us]')

In [45]:
df["transaction_date"].isnull().sum()

np.int64(0)

In [46]:
df["transaction_time"].str.len().value_counts()

transaction_time
5    550000
Name: count, dtype: int64

In [47]:
df["transaction_time"].head(10)

0    15:28
1    03:00
2    18:03
3    08:03
4    14:23
5    01:51
6    06:27
7    23:40
8    20:25
9    22:15
Name: transaction_time, dtype: str

In [48]:
df["transaction_datetime"] = pd.to_datetime(
    df["transaction_date"].dt.strftime("%Y-%m-%d") + " " + df["transaction_time"],
    format="%Y-%m-%d %H:%M",
    errors="coerce"
)

In [49]:
df[["transaction_date", "transaction_time", "transaction_datetime"]].head()

  transaction_date transaction_time transaction_datetime
0       2019-01-01            15:28  2019-01-01 15:28:00
1       2019-01-01            03:00  2019-01-01 03:00:00
2       2019-01-01            18:03  2019-01-01 18:03:00
3       2019-01-01            08:03  2019-01-01 08:03:00
4       2019-01-01            14:23  2019-01-01 14:23:00

In [50]:
df["transaction_datetime"].isnull().sum()

np.int64(0)

In [51]:
df["year"]=df["transaction_datetime"].dt.year
df["month"]=df["transaction_datetime"].dt.month
df["month_name"]=df["transaction_datetime"].dt.month_name()
df["day_of_week"]=df["transaction_datetime"].dt.day_name()
df["is_weekend"]=df["transaction_datetime"].dt.day_of_week>=5

In [52]:
df[
    ["transaction_datetime","year","month","month_name","day_of_week","is_weekend","transaction_hour"]
].head(10)

,transaction_datetime,year,month,month_name,day_of_week,is_weekend,transaction_hour
0,2019-01-01 15:28:00,2019,1,January,Tuesday,False,15
1,2019-01-01 03:00:00,2019,1,January,Tuesday,False,3
2,2019-01-01 18:03:00,2019,1,January,Tuesday,False,18
3,2019-01-01 08:03:00,2019,1,January,Tuesday,False,8
4,2019-01-01 14:23:00,2019,1,January,Tuesday,False,14
5,2019-01-01 01:51:00,2019,1,January,Tuesday,False,1
6,2019-01-01 06:27:00,2019,1,January,Tuesday,False,6
7,2019-01-01 23:40:00,2019,1,January,Tuesday,False,23
8,2019-01-01 20:25:00,2019,1,January,Tuesday,False,20
9,2019-01-01 22:15:00,2019,1,January,Tuesday,False,22

### EDA

In [56]:
df.groupby("year").agg(
    transactions=("transaction_id","count"),
    total_amount=("transaction_amount","sum"),
    avg_amount=("transaction_amount","mean"),
).sort_values("total_amount", ascending=False).round(2)    # round= reduces the number of decimal places to 2

      transactions  total_amount  avg_amount
year
2022        110247  3.344988e+09    30340.86
2020        109767  3.315647e+09    30206.23
2023        109584  3.265949e+09    29803.16
2019        110083  3.258465e+09    29600.08
2021        110024  3.253235e+09    29568.41
2024           295  1.061643e+07    35987.90

In [57]:
df.groupby("is_fraud").agg(
    transactions=("transaction_id","count"),
        total_amount=("transaction_amount","sum"),
        avg_amount=("transaction_amount","mean"),
).round(2)

          transactions  total_amount  avg_amount
is_fraud
0               545127  1.586684e+10    29106.69
1                 4873  5.820614e+08   119446.21

In [58]:
df[df["is_fraud"]==1].groupby("transaction_type")["transaction_amount"].agg(["count","sum","mean"]).round(2).sort_values("sum",ascending=False)

                  count           sum       mean
transaction_type
RTGS                611  3.856183e+08  631126.55
Cheque              256  1.060433e+08  414231.83
NEFT                581  6.921285e+07  119127.11
Net_Banking         326  1.099390e+07   33723.63
IMPS                624  5.432249e+06    8705.53
UPI                1211  1.606774e+06    1326.82
ATM_Withdrawal      456  1.118000e+06    2451.75
POS                 481  8.528792e+05    1773.14
Credit_Card         140  7.442579e+05    5316.13
Auto_Debit          187  4.388083e+05    2346.57

In [59]:
df.groupby("customer_id").agg(
    transactions=("transaction_id","count"),
    total_amount=("transaction_amount","sum"),
    avg_amount=("transaction_amount","mean")
).sort_values("total_amount",ascending=False).head(10).round(2)

             transactions  total_amount  avg_amount
customer_id
CUST038846             12   10169933.88   847494.49
CUST003107              7   10022645.83  1431806.55
CUST053927              6   10010139.02  1668356.50
CUST061467              5   10002756.74  2000551.35
CUST075635              6    9430525.65  1571754.28
CUST016632              9    8789643.87   976627.10
CUST052357              9    8693571.47   965952.39
CUST037024             10    8349530.44   834953.04
CUST056730              6    8267916.94  1377986.16
CUST044606              8    8260283.13  1032535.39

In [61]:
merchant_analysis = df.groupby("merchant_category").agg(
    transactions=("transaction_id", "count"),
    total_amount=("transaction_amount", "sum"),
    avg_amount=("transaction_amount", "mean")
).sort_values("total_amount", ascending=False).round(2)

merchant_analysis

                   transactions  total_amount  avg_amount
merchant_category
Retail                    66180  2.004895e+09    30294.57
Food & Dining             54776  1.650395e+09    30129.89
E-Commerce                54767  1.618021e+09    29543.71
Salary                    43937  1.332665e+09    30331.28
Travel                    44177  1.308025e+09    29608.73
Peer Transfer             38753  1.156195e+09    29834.98
Utilities                 38575  1.127987e+09    29241.41
Healthcare                33015  9.752505e+08    29539.62
Entertainment             32997  9.745293e+08    29533.88
Investment                27380  8.474247e+08    30950.50
Education                 27359  8.163123e+08    29837.07
Government                27508  8.074440e+08    29353.06
Fuel                      21929  6.972416e+08    31795.41
Insurance                 22020  6.296330e+08    28593.69
Real Estate               16627  5.028831e+08    30244.97

### BUSINESS KPIs

In [62]:
kpis={
    "total transactions":df["transaction_id"].nunique(),
    "total transaction value":df["transaction_amount"].sum(),
    "average transaction value":df["transaction_amount"].mean(),
    "total customers":df["customer_id"].nunique(),
    "fraud transactions":df["is_fraud"].sum(),
    "fraud rate":df["is_fraud"].mean()*100

}

pd.Series(kpis).round(2)

total transactions           5.500000e+05
total transaction value      1.644890e+10
average transaction value    2.990709e+04
total customers              7.991600e+04
fraud transactions           4.873000e+03
fraud rate                   8.900000e-01
dtype: float64

In [63]:
df.to_csv("../data/bank_transactions_cleaned.csv", index=False)